# Generated by Django 5.0.4 on 2024-04-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafftask', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
