# Generated by Django 5.0.4 on 2024-04-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='amenities',
            field=models.CharField(max_length=200),
        ),
    ]
